### PR TITLE
[REVIEW] Update Azure blog scripts to support RAPIDS 0.10

### PR DESCRIPTION
**Pull request by JohnZed**
This change updates the environment yml file in the Azure ML blog to support RAPIDS 0.10. I've tested it and confirmed that I can still run the whole notebook smoothly.

As a small addition, I added status reporting when launching the cluster. So you now see state transitions for the experiment you've launched and get a clean exception if the launch fails. You'll also see a direct link to the AzureML portal logs.

### CODE REVIEW

**Comment by taureandyernv** [comment]
@Salonijain27 can you review and ensure that these notebooks are good to go?

**Comment by JohnZed** [comment]
@jacobtomlinson - could you take a look at this? The changes are pretty small. Thanks!

**Comment by JohnZed** [comment]
Thank you, Jacob! @taureandyernv - can you merge when you get a chance? We'll be presenting it in the near future and would like to present with rapids 0.10.

**Comment by jacobtomlinson** [comment]
@JohnZed I don't have merge rights here I'm afraid.

**Comment by taureandyernv** [comment]
@JohnZed merged on @jacobtomlinson 's review and approval

**Pull request merged**
