### PR TITLE
[REVIEW] Hello, BlazingSQL.

### PR DESCRIPTION
**Pull request by gumdropsteve**
- introduce /blazingsql/
- intermediate BlazingSQL demo notebooks

### CODE REVIEW

**Comment by taureandyernv** [comment]
@gumdropsteve let me know when to review

**Comment by gumdropsteve** [comment]
@taureandyernv ready for review

**Comment by gumdropsteve** [comment]
#### back to WiP
- move + modify "getting started" demos to getting started notebooks
- add install / setup instructions + info + `.sh` script(s)

**Comment by gumdropsteve** [comment]
**Update** Almost all done, added Taxi LinReg demo & other (see https://github.com/gumdropsteve/notebooks-contrib/pull/11). 

Still to do:
- add `.md` install / setup instructions 
- add `.sh` install script

**Comment by gumdropsteve** [comment]
Ready for review @taureandyernv

**Comment by gumdropsteve** [comment]
@taureandyernv fixed it and updated everything to reflect, thanks for clarifying over Slack.

**Pull request merged**
